# Sentiment analysis of kindle reviews using Word2Vec and RandomForest

##### Workflow
1. Preprocessing and clearning
2. Train test split
3. Word embeddings using Word2Vec
4. Training the model using RandomForest
5. testing the model

### Preprocessing and cleaning

In [35]:
import pandas as pd
df = pd.read_csv('all_kindle_review.csv')
df.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [36]:
df['reviewText'] = df['reviewText'] + df['summary']
df = df[['rating','reviewText']]

In [37]:
df.head()

   rating                                         reviewText
0       3  Jace Rankin may be short, but he's nothing to ...
1       5  Great short read.  I didn't want to put it dow...
2       3  I'll start by saying this is the first of four...
3       3  Aggie is Angela Lansbury who carries pocketboo...
4       4  I did not expect this type of book to be in li...

In [38]:
df.dropna(subset=['reviewText'], inplace=True)

In [39]:
from nltk import WordNetLemmatizer
lemmatizer = WordNetLemmatizer()

In [ ]:
import re
import nltk
from nltk.stem import WordNetLemmatizer
nltk.download('stopwords')
from nltk.corpus import stopwords
lemmatizer = WordNetLemmatizer()
corpus = []

for i in range(0, len(df)):
    X = re.sub('[^a-zA-Z]', ' ', df['reviewText'].iloc[i])
    X = X.lower()
    X = X.split()
    X = [lemmatizer.lemmatize(word) for word in X if not word in set(stopwords.words('english'))]
    X = ' '.join(X)
    corpus.append(X)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\goggl\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

['jace rankin may short nothing mess man hauled saloon undertaker know famous bounty hunter oregon shot man saloon finished year long quest avenge sister murder trying figure next snotty nosed farm boy rescued gang bully offer money kill man forced ranch reluctantly agrees bring man justice kill outright first need tell sister widower news kyla kyle springer bailey riding trail sleeping ground past month trying find jace want revenge man killed husband took ranch amongst crime keen detour jace want take realizes option hide behind boy persona best try keep pace confrontation along way get shot jace discovers kyle kyla come clean whole reason need scoundrel dead hope still help book share touching moment slow blooming romance kyla find good reason fear men hide behind boy persona watching jace slowly pull shell help conquer fear endearing pain real deeply rooted disappear face sexiness neither understandable aversion marriage magically disappear round nookie would man drifted town town entire adult life man killed fair share men along way feel make good husband father walking wounded unique position help need time realize however packed bursting favorite theme old west setting heroine passing male morally ambiguous hero wounded soul road romance kitchen sink certain distance writing kept getting carried away character distinct fully formed point glaring instance bland telling anything never felt really invested enjoyed quite bit exciting trip watching far away definitely run alongside add hasty tidy ending book left feeling bit less completely satisfied enjoyed book say average still read another book author note read released ebook version noticed lot formatting error missing word mentally edit read sentence make sense bad little distracting entertaining average',
 'great short read want put read one sitting sex scene great two male one female character bit surprising never thought could learned something new really enjoyed reading book great way get hot bothered take advantage significant terrific menage scene',
 'start saying first four book expecting conclude center child alex younger brother argus alex friend sapphire find name bus map find mystery start well written good character development although lot room still quite short book moving onto book swiftly snapdragon alley',
 'aggie angela lansbury carry pocketbook instead writing light murder mystery laced misdirection clue lead rather obvious cliche ending setting view described story best believable part aggie well written character light reading light murder cozy',
 'expect type book library pleased find price rightbook',
 'aislinn little girl big dream death older brother decides follow footstep become lady knight quest knighthood brings many challenge temptation forbidden love aislinn learns knight mean putting kingdom front personal concern helping cannot help journey fraught danger filled adventure aislinn forced grow fast must stay strong develop skill necessary realize lifelong dream sword fight passionate love mythical creature courtly game woman honor kind book love idea incorporating real history fantasy m zoltack book based real life story group female knight blending history fiction writing full plot adventure character strong believable grew love cared hardship success aislinn quite main protagonist tenacious bold beautiful strong romance bloom prince well developed year solid friendship teasing enjoyed reading secret courtship idea romance would turn m zoltack twist store shock startle well please conclusion thoroughly recommend book everyone enjoys fantasy romance adventure eagerly awaiting sequel knight glory story little girl big dream',
 'making good story unfortunately disappoints tell two alpha member unfriendly pack grown together one gay straight seems get together something happens story told alternating chapter past present story couple fall apart switch time lack sustainable reason break story potential ultimately disappoints',
 'got like collaborated short story alot time two good writer put head together result turn well case short story writer take age old lesson turn good read begin call crazy picking hitchhiker get graphic little much taste cut nutcase hitchhiking inevitably get together result suspenseful ending felt well deserved account also watched video two author decided break short story idea cool one wrote side scenario scenario without talking tier side going came bring two piece together made fit perfectly think took great talent two author take two seperate story merge well story pretty graphic detail forwarned mind little detail short story definitely pick one good thriller',
 'loved book hooked series hope kelsey maxwell really made character get enough loved',
 'good thing short sweet tease give everything quick kick kick come dark scared',
 'received copy book review secret society fanatical cult telepathic girl cup tea expected really need another continuational book still read catching fire hunger game get sci fi stuff cup tea sorry um',
 'even though already know outcome still enjoyable erotic read little short taste bit predictable',
 'read review decided give try despite review labeling brutal believe reviewer called brutal beyond disturbing read almost anything recognizing fiction returned less star rating available would used truly awful',
 'finished read wicked garden say wow even novella lorelei james write story hot e reader start smokin wicked garden short story lost love reuniting little extra sumthin sumthin billy buchanan return spearfish favor business associate agreed favor also would give chance ignite spark high school flame eden lacroix past ten year regretted walking away eden eden spent last ten year building career dedicated local community center helping risk kid time real relationship occasional string attached hook ups sexy native american rock star jon white feather billy eden see first time ten year chemistry spike chart eden determined fight billy working project could destroy job quickly sweet talk seeing side project thing heat eden billy realizing still strong feeling dunh dunh dunh jon come home couple day billy jon decide want give eden one darkest fantasy boy boy hot menage really like eden even though worried heart billy leaving take charge sexuality scared go want sexually much liked eden story billy jon stole story men sexy strong billy possessive sexy dominant vulnerable absolutely adore way treat eden insecurity display jon oh favorite get wrong love billy way jon treat eden menage melt heart among thing mention jon sexy rock star moon excited jon getting novella ballroom blitz release date folk let tell could get action went work room wicked garden would work room five ten time day wicked garden great novella perfect afternoon want escape hour bonus get see sexy lorelei writes non cowboy yep cowboy hat suit m james know write sexy hell hero sweet super sexy',
 'king james version far tell may know kjv published book included get ebook kjv apocrypha kindle bible kjv apocrypha best navigation direct verse jump orking james bible apocryphaorking james bible apocryphafor want read commentary book provided short intro misbach refer either halley bible handbookhalley bible handbook new international version deluxe editionor new unger bible handbookthe new unger bible handbook available kindle ebooks text credited',
 'disappointed book anything blond one figured joke good laugh wrong first count real surprised even joke book second among possible joke least repeated time different part book almost writer kept running list joke heard real concern whether might already recorded decided must least joke finally perfectly frank recall laughing single one joke better described insult mistaking degradation group people humor th grade material bother one worth cent even worth free pretty pathetic',
 'super quick book wish would longer really liked character sexy bedroom pool table sex good author nice fast read',
 'many time author going get amazon delete add comment alleged conspiracy people get f delusional review agree previous reviewer author know basic mechanic writing world written full star page filled grammar problem story suffers problem author inattention detail character inconsistent action like interchangeable peg board author put place need world highly rated',
 'love j r ward book story completely awsome zsadist favorite series wow',
 'first author thoroughly enjoyed say concept dragon elf djinn war new there usually truce place elf djinn team eliminate dragon mate attempt wipe dragon race refreshing read story wise mean scarlet pop star hiding year janos dragon also elder scarlet mate janos must protect till impregnate accomplished change thus giving way protect story short page still lot told short space looking forward continuing saga next book bad',
 'first anya bast book really liked looked read book seems little far fetched make book different menage story author took time really develop character men got know woman claim wisk screw like bunny took time woo loved respected honored also loved fact quite way book actually sex great read one would highly recommend would loved action intrigue part loved hope book becomes series great job m bast great menage',
 'love reading mini novel go wrong jane porter yet another great read amazingly talented author fell love estrella beautiful strong compassionate determined carlo man want hate instead end wishing enjoyed book beginning end character personality draw story line make want reach help less fortunate highly recommend mini novel perfect marriage love hate romance philanthropy heart warming story',
 'book extremely incredible read much heated passion describe every steele relationship glad brother cousin found passionate love last forged steele bundle',
 'difference guy man willingness take risk relationship woman course hot hot physical attraction explosive enjoyable earn star genre earned th star quality characterization interaction various character book book quick short read right palate pleaser want bit romance sex want commit sexy sassy short read',
 'gave half way much repetition much make sense hard follow shss story secret',
 'know expecting way form fashion book exciting think ordered wrong book accident satisfied',
 'love read simon wood book one morbid make reader victim skin crawl much guessing outright gruesome morbid',
 'short story confusing issue unreliable narrator difficult tell happening story writing poor reader able draw conclusion virtually everybody story difficulty relating others conversation begin trail without important information related author prevent normal interaction u able judge character one difficult understanding normal human interaction problem actually assumed main character mentally unbalanced waiting develop throughout story however story ended apparently become normal making unfulfilling conclusion set weird situation short story foreshadowing leave unexplored unexplained way author advance story tell u simple sentence type people character thing like nice person liked people know way never shown anything action story people put situation weird trailing conversation subjected basic statement type people environment realistic either odd wording thought first maybe story set another country character mention michigan sense place got story know michigan city hope anything specific place independent office supply story still business afford pay ten dollar hour part time help modern time hope anything specific happening character seem know thing would know example character war returned home worked another type job later old bruise face thought character war however human healing work way human aware bruise even old one relatively recent old trauma experience reading story kind like another specie writing human interaction know act way elephant interaction might make sense proofreading better earlier review stated going guess issue corrected still professional job',
 'found book enjoyable read first chapter really take keep entertained end enjoyed much immediately purchased next two book series city rogue',
 'amy parker going hawaii week christmas business give sex relationship focus career justin garrett traveling companion associate law firm work together definitely plane boldly masturbates seat next supposedly napping hears everything make hard left trip accidentally found racy email friend laptop know want know deepest darkest desire plan something hawaii meet client mitch magruder justin apprenticed going current job mitch justin share friendly camaraderie justin know count mitch help fulfill amy fantasy two work get amy relax unwind justin get relax enough give heart unwrapped jaci burton paint vivid picture two men coaxing amy letting go letting seduce reader enjoy molten hot eacute nage scene exquisite feeling finally intimate someone fantasized year m burton book power packed emotion sensuality love style creates believable intelligent character unwrapped suck page one keep riveted end highly recommended kiss pepper f eacute nage anal sex lindyreviewer twolips review llc kiss twolips review',
 'jodi birthday last place want stuck working bos boyfriend insists night job completed little choice jodi bos may mattress dancing decided early would string attached relationship lately jodi second thought relationship mark sound really good thing get interesting jodi get busted breaking entering sinfully sexy man mark rodriguez merge security company old buddy sam favor ask sam first mark would like sam join fulfilling jodi eacute nage fantasy birthday surprise however mark start second thought see jodi sam together perhaps mark want jodi string well private property spicy erotic novella eacute nage quite birthday surprise jodi mark jodi sam heat thing lusty novel like mark immediately reconsidering idea eacute nage relationship nothing like seeing woman getting another man make realize serious private property leave thinking breaking entering might bad thing mirandafor joyfully reviewed private property leave thinking breaking entering might bad thing',
 'interesting historic value really story rather accounting event interesting biographical information st person fact',
 'book detailed interesting felt time character much erotic got bored place tired savannah get book especially free good read different make say hummmm',
 'rd book second time still good exciting loving story sharing making sacrifice love life easy great story tender full angst',
 'type love ghost story enjoy book however someone else may enjoy never let people opinion put trying book look interesting said kind story mayhem',
 'believe listed romance read romance novel looking something uplifting book dark depressing find story writing bad depressing sex high overview go depth developement character relationship spoiler alert like happy ending forget said review guess strongly enough truly understand hopefully say plainly enough others expectation waste time hero dy brutal death saving heroine book continues several chapter showing remaining character pick life go end heroine sitting porch contemplating life wondering lie ahead man love gone almost cry end anger wasted free time reading book terrible ending',
 'read book twice make sure happy thought knew short book bought actually felt bad finsihed story line great charcters well thought however wish longer less rush get book finished great',
 'awesomee thriller hitched beginning dragged along roller coaster ride way end book great twist turn fell inlove main character girlfriend highly recommend next die',
 'ok story thought character little shallow pull brought together way fast booked moved sexy end blink felt like chapter get point maybe story taken place literally one place felt like really room growth story ended however well written term format would give another book author read sex hot storyline',
 'great twist turning mystery plot unable stop reading end definitely must read mystery suspense reader definitely recommend face creek',
 'think series first type story see james bond based bulldog drummond bulldog drummond chronicle',
 'book wrong many level although usually type spoiler one hope daughter one scientist lab wolfe held although mark refuse mate age lab burn wolfe believed dead year hope alone unable move another man bond hope evil mother apparently know wolfe survived sending photo hope men fake course wolfe appears nowhere capture hope punishes teasing sex allowing orgasm due mating heat apparently writhing pain continues try getting answer seek find nothing wrong get worse first time stick as finally decides innocent want relieve might rough animal surface course begs orgasm forgiven joking mother show quick falling sandbag thing take joke writing even good sex attempt story thrown worth buy',
 'story written badly struck emotionally tone deaf fiction abuse whether physical emotional take u place difficult place unfamiliar maybe sadly familiar story found thinking people act way think way thing little pat little rushed language bit careless observation little bit hard specify exactly seemed story almost reading collection story written somebody much exposure father child dynamic watching lifetime movie marathon emotionally tone deaf',
 'another light hearted novel hard put henry wright delightful character get tight spot springtime sonora',
 'never read author thoroughly enjoyed story would gladly read another disfigured hero fear pain pride wonderfully described felt wanting reach gently touch scar reassure exactly time aidan touched warwick get wrong warwick brutally strong hot male character privy thought within story began get protective feeling aidan acquired saw extremely handsome man warwick really passion romace well mixed much strengh wit character sometimes sure real hero story everyone like strong take matter hand heroine definately book one woman rescue squad perfect match mysterious masked hired guard warwick sex hot wicked well enjoy futuristic surprisingly strong heroine win day',
 'book deserving winner prestigious giller prize wanting read time wanted read boyden first book three day road first good book one even better good read three day road first precursor one helped understand character bit like three day road book difficult read way keep waiting terrible cataclysmic thing happen even though know going happen make less terrible book also similar three day road told viewpoint two different people young niece annie terrible story tell heals sharing highly recommend book would suggest read three day road first feel richer experience enjoying superlative story telling book take everyday life magical world seems real reading best book read far year',
 'amazon curse built relationship event developed vampire bride showalter book stand alone much better know back story rating would different already connected character reading previous book vampire bride focus layel king vampire delilah amazon warrior however introduced many character including zane nola happy find story ended would suggest using book alone introduction showalter writing missing good read previous book good read stand alone',
 'fan bound heart series perhaps best review book try two since reader romantic book see much romance sharing yuck',
 'stop reading series love character jacob especially victor relationship well plot always good bit mystery going adventure get know victor past voice usual something look forward really great series',
 'loved series seeing story family member together convenient best great compilation',

### Train Test Split

In [41]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(
    corpus,
    df['rating'],
    random_state=67,
    test_size=0.25
)

### Word embeddings

In [42]:
from gensim.models import Word2Vec
w2v = Word2Vec(
    sentences=x_train,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)
w2v_test = Word2Vec(
    sentences=x_test,
    vector_size=100,
    window=5,
    min_count=2,
    workers=4
)

In [43]:
import numpy as np
sentenc_vectors = []

for sent in x_train:
    vectors = []
    for word in sent:
        if word in w2v.wv:
            vectors.append(w2v.wv[word])
    if len(vectors) != 0:
        sentenc_vectors.append(np.mean(vectors, axis=0))
    else:
        sentenc_vectors.append(np.zeros(100))

In [44]:
len(sentenc_vectors)

8998

In [46]:
len(y_train)

8998

### Training the model

In [61]:
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()

In [62]:
classifier.fit(sentenc_vectors, y_train)

RandomForestClassifier()

### Testing the model

In [49]:
import numpy as np
x_test_vec = []

for sent in x_test:
    vectors = []
    for word in sent:
        if word in w2v.wv:
            vectors.append(w2v_test.wv[word])
    if len(vectors) != 0:
        x_test_vec.append(np.mean(vectors, axis=0))
    else:
        x_test_vec.append(np.zeros(100))

In [63]:
y_pred = classifier.predict(x_test_vec)

In [51]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [64]:
accuracy_score(y_pred=y_pred, y_true=y_test)

0.171

In [65]:
print(confusion_matrix(y_pred, y_test))

[[364 391 387 581 609]
 [  4   0   4   3   6]
 [  1   1   0   0   1]
 [ 61  55  49  77 119]
 [ 50  44  44  77  72]]

In [66]:
print(classification_report(y_pred, y_test))

              precision    recall  f1-score   support

           1       0.76      0.16      0.26      2332
           2       0.00      0.00      0.00        17
           3       0.00      0.00      0.00         3
           4       0.10      0.21      0.14       361
           5       0.09      0.25      0.13       287

    accuracy                           0.17      3000
   macro avg       0.19      0.12      0.11      3000
weighted avg       0.61      0.17      0.23      3000

In [55]:
from sklearn.linear_model import LogisticRegression

classifier = LogisticRegression(max_iter=1000)

In [59]:
classifier.fit(sentenc_vectors, y_train)

LogisticRegression(max_iter=1000)

In [60]:
accuracy_score(y_pred=y_pred, y_true=y_test)

0.187